import streamlit as st
import pandas as pd
import joblib

# ------------------------
# Load model and data
# ------------------------

# Trained logistic regression model + feature list (from your training script)
model = joblib.load("cardio_log_reg_model.joblib")
features = joblib.load("cardio_features.joblib")

# Dataset for analytics
df = pd.read_csv("cardio.csv", sep=";")
df["age_years"] = (df["age"] / 365.25).astype(int)

# ------------------------
# App title
# ------------------------

st.title("Cardiovascular Disease Risk Estimator & Data Explorer")
st.write(
    "This app uses a logistic regression model trained on a cardiovascular dataset "
    "to estimate the probability of cardiovascular disease and explore how each "
    "variable behaves in the data.\n\n"
    "**For educational purposes only – not medical advice.**"
)

# ------------------------
# Tabs: Risk Estimator | Data Explorer
# ------------------------

tab_predict, tab_explore = st.tabs(["Risk Estimator", "Data Explorer"])

# ============================================================
# TAB 1 — RISK ESTIMATOR
# ============================================================

with tab_predict:
    st.header("Enter Your Information")

    col1, col2 = st.columns(2)

    with col1:
        age_years = st.slider("Age (years)", min_value=29, max_value=64, value=50)
        ap_hi = st.slider("Systolic BP (ap_hi)", min_value=80, max_value=240, value=130)
        ap_lo = st.slider("Diastolic BP (ap_lo)", min_value=40, max_value=150, value=80)
        weight = st.slider("Weight (kg)", min_value=40, max_value=150, value=75)

    with col2:
        cholesterol = st.selectbox(
            "Cholesterol level",
            options=[1, 2, 3],
            format_func=lambda x: {
                1: "Normal (1)",
                2: "Above Normal (2)",
                3: "Well Above Normal (3)"
            }[x]
        )
        gluc = st.selectbox(
            "Glucose level",
            options=[1, 2, 3],
            format_func=lambda x: {
                1: "Normal (1)",
                2: "Above Normal (2)",
                3: "Well Above Normal (3)"
            }[x]
        )
        smoke = st.selectbox(
            "Do you smoke?",
            [0, 1],
            format_func=lambda x: "Yes" if x == 1 else "No"
        )
        alco = st.selectbox(
            "Do you frequently drink alcohol?",
            [0, 1],
            format_func=lambda x: "Yes" if x == 1 else "No"
        )
        active = st.selectbox(
            "Are you physically active?",
            [0, 1],
            format_func=lambda x: "Yes" if x == 1 else "No"
        )

    if st.button("Estimate Risk", key="predict_button"):
        # Build input row in the same order as training
        input_dict = {
            "age_years": age_years,
            "ap_hi": ap_hi,
            "ap_lo": ap_lo,
            "cholesterol": cholesterol,
            "gluc": gluc,
            "smoke": smoke,
            "alco": alco,
            "active": active,
            "weight": weight,
        }

        input_df = pd.DataFrame([[input_dict[col] for col in features]], columns=features)

        prob = model.predict_proba(input_df)[0, 1]
        pred = model.predict(input_df)[0]

        st.subheader("Estimated Probability of Cardiovascular Disease")
        st.write(f"### **{prob:.2%}**")

        if pred == 1:
            st.error("The model predicts: **Higher risk (cardio = 1)**")
        else:
            st.success("The model predicts: **Lower risk (cardio = 0)**")

        st.caption(
            "This prediction is generated by a class project model and is "
            "**not** a substitute for professional medical evaluation."
        )

# ============================================================
# TAB 2 — DATA EXPLORER
# ============================================================

with tab_explore:
    st.header("Explore the Dataset")

    variable = st.selectbox(
        "Choose a variable to explore:",
        ["age_years", "ap_hi", "ap_lo", "cholesterol", "gluc", "weight", "smoke", "alco", "active"],
        key="explore_variable"
    )

    st.subheader("Summary Statistics")
    st.write(df[variable].describe())

    st.subheader("Distribution")

    # If the variable has only a few unique values (categorical-like), show value counts
    if df[variable].nunique() <= 15:
        dist = df[variable].value_counts().sort_index()
        st.bar_chart(dist)
    else:
        # For more continuous variables, show the raw values as a basic chart
        st.bar_chart(df[[variable]])

    st.subheader("Average Value by Cardiovascular Disease Status")
    st.write(df.groupby("cardio")[variable].mean().rename("mean_" + variable))

    st.subheader("Correlation With Cardiovascular Disease")
    st.write(df[["cardio", variable]].corr())

